language: python
dist: xenial

python:
  - "2.7"

matrix:
  include:
    - os: osx
      language: sh
      python: "2.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew install unix2dos
        - pip install pyinstaller wxpython pyxform
      script:
        - ./make-mac.sh
    - os: windows
      language: sh
      python: "2.x"
      before_install:
        - choco install python2 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python get-pip.py
        - pip install pyinstaller
      script:
        - ./make-win.bat

