os:
  - osx
  - linux

dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install unix2dos; fi
  - pip install pyinstaller wxpython pyxform

# Command to run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./make-mac.sh; else ./make-win.bat; fi
